### ISSUE TITLE
Doesn't build in 5.25 now that -DPERL_OP_PARENT is the default.

### ISSUE THREAD

**Issue by mat813** [Sereal/Sereal#136]
According to perl5220delta, the sibling information should be accessed through macros.

```
cc -c  -I.  -O2 -pipe  -fstack-protector -fno-strict-aliasing -O3 -Werror=declaration-after-statement    -DVERSION=\"3.014\"  -DXS_VERSION=\"3.014\" -DPIC -fPIC "-I/usr/local/lib/perl5/5.25/mach/CORE"  -DNDEBUG Decoder.c
Decoder.xs:196:20: error: no member named 'op_sibling' in 'struct op'
    if ( ! pushop->op_sibling )
           ~~~~~~  ^
Decoder.xs:198:26: error: no member named 'op_sibling' in 'struct op'
    firstargop = pushop->op_sibling;
                 ~~~~~~  ^
Decoder.xs:200:35: error: no member named 'op_sibling' in 'struct op'
    for (cvop = firstargop; cvop->op_sibling; cvop = cvop->op_sibling) ;
                            ~~~~  ^
Decoder.xs:200:60: error: no member named 'op_sibling' in 'struct op'
    for (cvop = firstargop; cvop->op_sibling; cvop = cvop->op_sibling) ;
                                                     ~~~~  ^
Decoder.xs:206:43: error: no member named 'op_sibling' in 'struct op'
        lastargop = argop, argop = argop->op_sibling
                                   ~~~~~  ^
Decoder.xs:225:13: error: no member named 'op_sibling' in 'struct op'
    pushop->op_sibling = cvop;
    ~~~~~~  ^
Decoder.xs:226:16: error: no member named 'op_sibling' in 'struct op'
    lastargop->op_sibling = NULL;
    ~~~~~~~~~  ^
7 errors generated.
```

**Comment by tsee** [comment]
Should be fixed in fc92dbea27d03059ce119ee9f3b6a06ca3a97ec7.
